{
 "title": "Traefik",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "service",
    "query": "label_values(traefik_service_requests_total,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response codes by entrypoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (xxcode, entrypoint) (label_replace(rate(traefik_entrypoint_requests_total{code=~\"^2..$\"}[5m]), \"xxcode\", \"2xx\", \"code\", \".*\"))",
     "legendFormat": "2xx {{entrypoint}}"
    },
    {
     "expr": "sum by (xxcode, entrypoint) (label_replace(rate(traefik_entrypoint_requests_total{code=~\"^3..$\"}[5m]), \"xxcode\", \"3xx\", \"code\", \".*\"))",
     "legendFormat": "3xx {{entrypoint}}"
    },
    {
     "expr": "sum by (xxcode, entrypoint) (label_replace(rate(traefik_entrypoint_requests_total{code=~\"^4..$\"}[5m]), \"xxcode\", \"4xx\", \"code\", \".*\"))",
     "legendFormat": "4xx {{entrypoint}}"
    },
    {
     "expr": "sum by (xxcode, entrypoint) (label_replace(rate(traefik_entrypoint_requests_total{code=~\"^5..$\"}[5m]), \"xxcode\", \"5xx\", \"code\", \".*\"))",
     "legendFormat": "5xx {{entrypoint}}"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "service" },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Request response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",code=~\"^2..$\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",code=~\"^3..$\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",code=~\"^4..$\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",code=~\"^5..$\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "rate(traefik_service_request_duration_seconds_sum{service=\"$service\"}[5m]) / rate(traefik_service_request_duration_seconds_count{service=\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP verbs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",method=\"GET\"}[5m])) by (code)",
     "legendFormat": "GET {{code}}"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",method=\"POST\"}[5m])) by (code)",
     "legendFormat": "POST {{code}}"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",method=\"PATCH\"}[5m])) by (code)",
     "legendFormat": "PATCH {{code}}"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\",method=\"DELETE\"}[5m])) by (code)",
     "legendFormat": "DELETE {{code}}"
    }
   ]
  }
 ]
}